### ISSUE TITLE
[RFC] Make `/users` route public 

### ISSUE THREAD

**Issue by heyrandhir** [Real-Dev-Squad/website-backend#1045]
# Remove authentication for /users route

- The /users route currently requires authentication.
- Only registered users of our RDS can access the /users route.
- To make services such as user management open to the public, authentication would need to be removed.
- Removing authentication would allow anyone to access these services without needing to register or log in.
- It's important to carefully consider the potential security implications before removing authentication.

**Comment by RitikJaiswal75** [comment]
Here is my take on it
- The /users API does not return important data and is managed by controllers.
- It may be possible to remove authentication from the /users route.
- The /users route is currently authenticated while the /users/username route is not. So it feels kind of weird
- Before making any changes, it's important to carefully consider the potential security implications.
- Removing authentication should not compromise the security of our system or expose sensitive data.

**Comment by vikhyat187** [comment]
Hi @RitikJaiswal75 @heyrandhir, we already had [discussion with Ankush](https://discord.com/channels/673083527624916993/735598747949465640/1098671082766094537) on this change and we decided to go with this, as one of the ticket which requires to change the `/users/userId/:id` API has to be included in the `/users/?id=abc` and since the `/users/userId/:id` is unauthenticated, we need to make the `users/` API unauthenticated as well.
I've checked we don't pass the personal info in the users API, so we can remove auth, I feel.

The ticket to track the changes is https://github.com/Real-Dev-Squad/website-backend/issues/983 Ujjawal is working on that.
