### ISSUE TITLE
Fix data obfuscation and ID field issues in updateUser function

### ISSUE THREAD

**Issue by lakshayman** [Real-Dev-Squad/website-backend#2223]
### Issue Description
The `updateUser` function in `controllers/users.js` has two critical issues:
1. It merges obfuscated email and phone number data into the user record.
2. It incorrectly includes an `id` field when updating user data, potentially causing conflicts with the document's actual ID.

### Expected Behavior
1. The function should merge unobfuscated email and phone number data into the user record.
2. The `id` field should be excluded when updating user data.

### Current Behavior
1. Obfuscated email and phone number data from `fetchProfileDiff` are being merged into the user record.
2. An `id` field is included in the data used to update the user record, which may interfere with the document's actual ID.

### Screenshots
N/A

### Reproducibility

 - [x] This issue is reproducible
 - [ ] This issue is not reproducible

### Steps to Reproduce
1. Call the `updateUser` function with a valid `profileDiffId`.
2. Check the updated user record in the database.
3. Observe that the email and phone number are obfuscated and an extra `id` field is present.

### Severity/Priority
 - [ ] Critical
 - [x] High
 - [ ] Medium
 - [ ] Low

### Additional Information
The `fetchProfileDiff` function returns obfuscated data for UI purposes, but this data is being directly used to update the user record. We need to implement a way to get both obfuscated (for UI) and unobfuscated (for database updates) data.

### Proposed Solution
1. Create a new function in `profileDiffsQuery` that returns unobfuscated data for database updates.
2. Modify the `updateUser` function to use this new function for getting unobfuscated data.
3. Implement a filtering step to remove the `id` field before updating the user record.

### Checklist

- [x] I have read and followed the project's code of conduct.
- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand and reproduce the issue.
- [x] I am willing to contribute to the resolution of this issue.

**Comment by RahulGoyal-tech** [comment]
Hello,
Code Reference : models/users.js - addOrUpdate function
In addOrUpdate function, we are setting 2 objects in firestore. As per my understanding, user.data() takes in current data and re sets it in the document and then userData updates the profileDiff fields. If i am correct, then to resolve the above issue, should i also remove id field from user.data() object as well and userData because if i only remove it from userData then if a document has an id set previously due to bug, it would still continue to exist even after setting profile diff with filtered out id field.
