### ISSUE TITLE
GET new members who recently signed up

### ISSUE THREAD

**Issue by ankushdharkar** [Real-Dev-Squad/website-backend#262]

**Comment by rajakvk** [comment]
We may use existing [/members](https://github.com/Real-Dev-Squad/website-backend/issues/238) with additional query

### Existing
/members
/members?userType=<new|member|blocked> ([refer](https://github.com/Real-Dev-Squad/website-backend/issues/238))

### Proposing
/members?userType=new&since=date

@sumitd94 @ankushdharkar @Kratika0907

**Comment by ankushdharkar** [comment]
@rajakvk New users are not members by default.

I'd like to instead suggest calling this /users?type=new

**Comment by sumitd94** [comment]
This PR linked with this issue (#296 ) should only be merged after successfully running/merging this PR #351
